apiVersion: v1
kind: Service
metadata:
  name: apiway-smtp
  labels:
    name: apiway-smtp
    kubernetes.io/name: "apiway-smtp"
spec:
  type: LoadBalancer
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
    - name: smtp-ssl
      port: 465
      targetPort: 465
      protocol: TCP
    - name: smtp-starttls
      port: 587
      targetPort: 587
      protocol: TCP
  selector:
    role: apiway-smtp
