apiVersion: v1
kind: Service
metadata:
  name: apiway-pubsub
  labels:
    name: apiway-pubsub
    kubernetes.io/name: "apiway-pubsub"
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
  selector:
    role: apiway-pubsub
