apiVersion: v1
kind: Service
metadata:
  name: apiway-report
  labels:
    name: apiway-report
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    role: apiway-report
