apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiway-pubsub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: apiway-pubsub
        name: apiway-pubsub
    spec:
      containers:
      - image: 539277938309.dkr.ecr.us-west-2.amazonaws.com/apiway-pubsub:latest
        name: apiway-pubsub
        ports:
        - containerPort: 1883
