apiVersion: v1
kind: Service
metadata:
  name: apiway-report
  labels:
    name: apiway-report
    kubernetes.io/name: "apiway-report"
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
  selector:
    role: apiway-report
