apiVersion: v1
kind: Service
metadata:
  name: apiway-api
  labels:
    name: apiway-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: apiway-api
