apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-schedule
spec:
  serviceName: "mongo-schedule"
  replicas: 2
  template:
    metadata:
      labels:
        role: mongo-schedule
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-schedule-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo-schedule,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: mongo-schedule-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "generic"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
