apiVersion: v1
kind: Service
metadata:
  name: mongo-schedule
  labels:
    name: mongo-schedule
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo-schedule
